export const ActionTypes ={
    ADD_TO_CART : "ADD_TO_CART",
    FETCH_PRODUCTS : "FETCH_PRODUCTS",
    SET_PRODUCTS : "SET_PRODUCTS",
    SELECTED_PRODUCT: "SELECTED_PRODUCT",
    REMOVE_SELECTED_PRODUCT : "REMOVE_SELECTED_PRODUCT",
}